# LOCAL_MODEL_NAME = "qwen3-coder:latest"
# LOCAL_MODEL_NAME = "qwen3:latest"
# LOCAL_MODEL_NAME = "deepseek-r1:latest"
# LOCAL_MODEL_NAME = "qwen2.5-coder:latest"
LOCAL_MODEL_NAME = "mistral:latest"
LOCAL_MODEL_PORT = "11434"