coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: 100%
        threshold: 1%
        informational: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "docs/"
  - "test/"
  - "**/test_*.py"
  - "setup.py"
  - "conftest.py"
  - "README.md"
  - "LICENSE"
