name: Publish to PyPI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      test_pypi:
        description: 'Set to true to publish to TestPyPI only'
        required: false
        default: 'false'
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    # Only publish on push to main
    if: github.event_name == 'push'
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Check package
        run: python -m twine check dist/*

      # publish to TestPyPI on push
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user:  ${{ secrets.TEST_PYPI_USERNAME }}
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          verbose: true
      # Publish to PyPI (on release)
      - name: Publish to PyPI
        if: ${{ github.event.inputs.test_pypi != 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user:  ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true